ArnesSI/netbox-inventory

netbox_inventory/navigation.py

for example - when not logged into netbox, menu items for plugin still showed up, but selecting any of them redirected to login screen
not menu items are hidden if user does not have view permission

only show menu items if user has permissions

---

netbox_inventory/forms/bulk.py

Two fixes related to validation and returning properly errors:
- when validating uniqueness on Asset, device_type, module_type and inventoryitem_type were excluded from checks so a check for duplicate device_type&serial would not occur for example
- auto-creating related objects is moved to pre-validation stage so any errors there can be returned and shown to user

Asset CSV import fixes

---

netbox_inventory/forms/create.py

fix for #38 
when using create device from asset and assigning tags, assigned_asset field was cleared by BaseModelForm._save_m2m()

fix creating device from asset with tags

---

netbox_inventory/forms/bulk.py

On Asset import if `asset_import_create_inventoryitem_type` is enabled and InventoryItem Type does not exist, it is created with empty `model` field. This causes import to fail.
Fix for this and also enable case insensitive check for device type and modules type names.

when creating related objects, make sure to pass model value

---

.github/workflows/test.yml
README.md
netbox_inventory/forms/create.py
netbox_inventory/models.py
netbox_inventory/signals.py
netbox_inventory/tests/asset/test_models.py
netbox_inventory/tests/asset/test_views.py
netbox_inventory/utils.py

Fix issues related to changing asset and assigned hardware relations:
- when you tried to unassign device from asset it returned error: `'Cannot change device serial and asset tag if asset is assigned. Please update via inventory > asset instead.'`
- when a device assigned to an asset was deleted, the assigned asset status was not updated
- error when creating InventoryItem from Asset in netbox v3.4.2 and later (#55)

Fix asset sync

---

netbox_inventory/navigation.py

Added a top level navigation element as it is now supported in NetBox 3.4 and moved all the links from the plugins menu to the new dedicated menu.

Updated navigation menu for NetBox 3.4

---

README.md
netbox_inventory/__init__.py
netbox_inventory/navigation.py

continuing from #48 and keeping in mind comment by @ryanmerolle I've added an option to add navigation items to it's own menu, or keep them under plugins as implemented in https://github.com/ryanmerolle/netbox-acls/pull/113
Also kept compatibility with netbox v3.3.x for now.

make top level menu configurable and support netbox 3.3

---

netbox_inventory/api/nested_serializers.py
netbox_inventory/api/serializers.py
netbox_inventory/tests/asset/test_api.py
netbox_inventory/tests/inventoryitem_group/test_api.py
netbox_inventory/tests/inventoryitem_type/test_api.py
netbox_inventory/tests/purchase/test_api.py
netbox_inventory/tests/supplier/test_api.py

API serializers were missing fields and some fields were marked as mandatory even if thew weren't. This happened mainly for model fields that are used in unique_together, but can also be Null. So we need to remove default validators generated by django rest framework. See [DRF docs](https://www.django-rest-framework.org/api-guide/validators/#optional-fields) fore details.
Also add unit tests for API endpoints
fixes #60

Fix REST API serializers

---

netbox_inventory/models.py
netbox_inventory/templates/netbox_inventory/asset.html
netbox_inventory/templates/netbox_inventory/inventoryitemtype.html

Asset and InventoryItemType can now have images uploaded and attached. For implementation I used ModuleType from netbox core as an example.
No migration/database schema change is needed for GenericRelation fields.
closes #46

add option to attach images to Asset and InventoryItemType

---

netbox_inventory/filtersets.py
netbox_inventory/forms/filters.py
netbox_inventory/models.py
netbox_inventory/tables.py
netbox_inventory/templates/netbox_inventory/supplier.html

Supplier can have multiple contacts assigned, each with a role and priority. The same was as netbox Provider or Site model handle contacts assignment.
For REST API: Getting and manipulating contact assignments to Supplier is done via `/api/tenancy/contact-assignments/` URL where: `conntent_type=netbox_inventory.supplier`.
closes #61

add option to assign contacts to supplier

---

netbox_inventory/templates/netbox_inventory/asset.html

- only show buttons to assign asset to hardware and to create hardware from asset if user has needed permissions
-  show inventory item type group asset belongs to

improve Asset details

---

netbox_inventory/api/serializers.py
netbox_inventory/tests/asset/test_api.py

This makes for example POST asset endpoint accept:
```
{
"serial": "1",
"status": "stored",
"device_type": 1,
"device": null
}
```
Previously you had to omit the keys without value:
```
{
"serial": "1",
"status": "stored",
"device_type": 1
}
```
fixes #60

make API endpoint accept null for optional keys that are relations

---

netbox_inventory/models.py
netbox_inventory/signals.py
netbox_inventory/templates/netbox_inventory/asset.html
netbox_inventory/tests/asset/test_models.py
netbox_inventory/tests/asset/test_views.py
netbox_inventory/tests/settings.py
netbox_inventory/utils.py

If setting sync_hardware_serial_asset_tag is set to True and you try to create hardware from asset that has a blank serial, you get an error "Cannot change inventoryitem serial and asset tag if asset is assigned. Please update via inventory > asset instead."
This happens also if you try to edit and save inventoryitem that has asset with blank serial assigned.
Applies not just to inventoryitems but to modules and devices as well.
Signal handler did not compare "blank" serial values correctly. Asset.serial blank is None (because of uniqueTogether constraints, but device.serial blank is empty string)
fixes #80 #81

fix sync_hardware_serial_asset_tag when asset serial blank

---

netbox_inventory/template_content.py
netbox_inventory/templates/netbox_inventory/inc/asset_stats_counts.html
netbox_inventory/templates/netbox_inventory/inc/asset_tenant.html
netbox_inventory/templates/netbox_inventory/inventoryitemtype.html
netbox_inventory/views/inventoryitem_type.py

On Manufacturer, Device Type, Module Type, Contact, Tenant and Inventory Item Type we shoe count of assets related to that object. And links to filtered Asset list.
closes #14

Show count of related assets throughout netbox

---

netbox_inventory/forms/bulk.py

in `_create_related_objects()` we call field's `.clean()` method for some properties of related objects (like `model_comments`). However when doing update rather than import, fields not given in CSV are removed from `self.fieds`. That resulted in `KeyError` when `model_comments` (and possibly others) was not specified. Rather than accessing field via `self.field`, we use `self.base_fields` that has all the fields still

fix bulk update via CSV when some fields were not specified

---

netbox_inventory/templates/netbox_inventory/asset.html
netbox_inventory/templates/netbox_inventory/inventoryitemgroup.html
netbox_inventory/templates/netbox_inventory/inventoryitemtype.html
netbox_inventory/templates/netbox_inventory/purchase.html
netbox_inventory/templates/netbox_inventory/supplier.html

Make use of `plugin_right_page` `plugin_left_page` and `plugin_full_width_page` so other plugins can inject content into object detail views

extend detail templates to accept content injected by other plugins

---

README.md
netbox_inventory/__init__.py
netbox_inventory/filtersets.py
netbox_inventory/utils.py

This pull request adds support for search on custom fields. It supports different lookup types which need to be specified in configuration.
Example of config:
```python
{
'asset_custom_fields_search_filters': { 'asset_mac': ['exact'], 'another_one': ['icontains', 'exact']}
}
```

Add: search support for custom fields

---

netbox_inventory/api/serializers.py
netbox_inventory/tests/asset/test_api.py

assigning empty string to asset serial or asset_tag via API, normalizes to None

---

netbox_inventory/forms/bulk.py
netbox_inventory/tests/asset/test_api.py
netbox_inventory/tests/asset/test_models.py
netbox_inventory/tests/asset/test_views.py

If you had multiple Purchases with the same name but different Suppliers or multiple Deliveries with same name but from different Purchases, the CSV import failed because it searched only on name.
I replaced `CSVModelChoiceField` with `CharFields` and am getting the correct Purchase & Delivery instances in `AssetImportForm.clean_<field>` methods, where I have access to all columns.

Fix Asset import with Purchase & Delivery info

---

netbox_inventory/templates/netbox_inventory/delivery.html
netbox_inventory/templates/netbox_inventory/purchase.html
netbox_inventory/templates/netbox_inventory/supplier.html
netbox_inventory/views/delivery.py
netbox_inventory/views/purchase.py
netbox_inventory/views/supplier.py

Instead of creating tables in view and rendering in template, we include tables using HTMX. Initial page load will be faster since additional tables load in background.
This is what core netbox moved to in most detail views.
also fixes #126

use htmx to include asset table on detail views

---

netbox_inventory/forms/assign.py
netbox_inventory/forms/reassign.py

- Solves #120 
- Clear any custom fields while assigning/reassigning `Asset` to models that inherit from `AssetAssignMixin`/`AssetReassignMixin`

Remove CF from assign/reassign forms

---

netbox_inventory/models.py

validate that warranty start and end dates make sense

---

netbox_inventory/forms/bulk.py

On bulk edit forms, date fields were just CharFields instead of using DatePicker widget.
fixes #142

date fields on bulk edit forms use correct widget

---

netbox_inventory/navigation.py

The Netbox Inventory plugin serves two purposes: It manages assets and it manages the process around deliveries. Now they are separated in the menu for easier navigation.

Arrange menu items

---

netbox_inventory/filtersets.py

The asset ID is often used as identifier for assets. This patch adds id to the searched attributes in the asset listing.

Add id to search for asset attributes

---

netbox_inventory/models.py
netbox_inventory/tables.py

A linked count column added to the device and module type list tables allows for quick access to the associated assets, while providing an overview of the total assets managed as opposed to instances in use. This also allows both columns to be exported as CSV.

Add device and module type columns

---

netbox_inventory/template_content.py

not needed from netbox v4.0.6 & #161. 
On device type details and module type details links to related assets are automatically shown under related objects so there is no need for the extra panel anymore.
thanks to @alehaa

remove template extensons for device & module types

---

netbox_inventory/forms/filters.py
netbox_inventory/utils.py

some fields don't make sense to filter for none. and some result in queries that return unexpected results
Removed option None from:
- Installed at location
- Installed in rack
- Installed in device
- Located at location

remove option to filter for None in some location related filters

---

README.md
netbox_inventory/forms/reassign.py
netbox_inventory/models.py
netbox_inventory/utils.py

When reassigning asset for a device or module, allow selecting an asset with a different device_type or module_type as the current one on device (or module).
If setting `sync_hardware_serial_asset_tag` is `True`, the device or module device type/module_type will be updated automatically as well. However updating any components of device or module to match the new type is not handled by this plugin.

allow changing device_type and module_type

---

netbox_inventory/models.py

ensure change snapshots are created for hardware when changing hw - asset relations
when going through "edit assignment" to change a device related to asset, there was not snapshot created for old or new device, so object change diff view was incomplete.

ensure change snapshots are created for hardware

---

README.md
netbox_inventory/__init__.py
netbox_inventory/utils.py

Add two more plugin settings: `used_additional_status_names` and `stored_additional_status_names`. These are used when filtering assets by location - any asset that has storage location (or site) set to a location and has status from  `stored_additional_status_names` in addition to `stored_status_name` will be considered as currently stored at location.

add ability to mark multiple asset statuses as used or stored

---

netbox_inventory/tables.py

The current location of an asset is mapped to either its assigned object's location or its storage location. Since these are multiple database fields that cannot be clearly sorted without complex annotations, sorting will be disabled for these columns to prevent errors when using the table.
Fixes: #245

Fixes #245: Disable column sorting for current asset location

---

netbox_inventory/tables.py
netbox_inventory/tests/audittrailsource/test_filtersets.py

The lifetime column was a leftover from previous development intended for audit trails and never reached production. It can be removed from tables and filtersets because it is not available on the related model.

Remove superflous audit trail source column
