ArnesSI/netbox-inventory

netbox_inventory/template_content.py
=> update template context only if we have an asset

netbox_inventory/forms/__init__.py, netbox_inventory/forms/bulk_add.py, netbox_inventory/templates/netbox_inventory/asset_bulk_add.html, netbox_inventory/templates/netbox_inventory/asset_edit.html, netbox_inventory/templates/netbox_inventory/inc/asset_edit_header.html, netbox_inventory/tests/asset/test_views.py, netbox_inventory/urls.py, netbox_inventory/views/asset.py
see #13 
I've added a new bulk create tab for assets. You can specify a number of assets to create and that many will be created. You cannot specify serial and asset tag. All created assets will have the same values. The only difference will be `Asset.id`.
=> Bulk asset create

README.md, netbox_inventory/choices.py, netbox_inventory/filtersets.py, netbox_inventory/forms/bulk.py, netbox_inventory/forms/filters.py, netbox_inventory/models.py, netbox_inventory/utils.py
and mention the functionality in README.md
=> Fix choices name

netbox_inventory/signals.py
=> update asset.status via signal when assigned hardware is deleted

netbox_inventory/forms/create.py, netbox_inventory/signals.py
=> move asset to hardware assignment logic from signal to form

netbox_inventory/forms/bulk.py, netbox_inventory/models.py, netbox_inventory/signals.py, netbox_inventory/utils.py
=> prevent changing serial or asset_tag for hardware that has asset assigned

netbox_inventory/forms/bulk.py, netbox_inventory/templates/netbox_inventory/asset_bulk_import.html, netbox_inventory/tests/asset/test_views.py, netbox_inventory/views/asset.py
Improved Asset CSV import:
- renamed hardware_type column to model_name
- added part_number column
- improved help and added explanation how related objects get auto.created
- fixed importing with purchase_date
closes #34
=> Asset import improvements

netbox_inventory/models.py, netbox_inventory/tables.py
Addresses issue 42 and some more verbose name standardization.
See https://github.com/ryanmerolle/netbox-acls for reference.
=> Standardize Verbose Names in models

netbox_inventory/templates/netbox_inventory/inventoryitemtype.html
=> Inventory Item Types: make Manufacturer clickable

netbox_inventory/tables.py
=> in asset table, display ID by default

netbox_inventory/forms/bulk.py, netbox_inventory/navigation.py, netbox_inventory/tests/inventoryitem_group/test_views.py, netbox_inventory/tests/inventoryitem_type/test_views.py, netbox_inventory/tests/purchase/test_views.py, netbox_inventory/tests/supplier/test_views.py, netbox_inventory/urls.py, netbox_inventory/views/inventoryitem_group.py, netbox_inventory/views/inventoryitem_type.py, netbox_inventory/views/purchase.py, netbox_inventory/views/supplier.py
=> add import & bulk edit for all models

netbox_inventory/analyzers.py, netbox_inventory/tables.py, netbox_inventory/templates/netbox_inventory/inventoryitemgroup.html, netbox_inventory/views/inventoryitem_group.py
add count of inventory item types contained by an inventory item group
And fix & optimize report of asset county by inventory item type and status.
=> improve inventory item group child element counts

netbox_inventory/tables.py
=> add column comments to asset table

README.md
=> update example settings in README

netbox_inventory/filtersets.py, netbox_inventory/forms/filters.py
Make sure saved filter field shows up in all filter forms
Also when performing general search on assets, filter asset_tag as icontains instead of iexact
=> support saved filters

netbox_inventory/templates/netbox_inventory/inc/asset_info.html
also on module detail and inventory item detail views
=> nicer display of assinged asset on device detail view

netbox_inventory/forms/bulk.py
=> enable import of tags for assets

netbox_inventory/forms/bulk_add.py, netbox_inventory/forms/models.py, netbox_inventory/templates/netbox_inventory/asset_bulk_add.html, netbox_inventory/templates/netbox_inventory/asset_edit.html, netbox_inventory/views/asset.py, netbox_inventory/views/asset_create.py
On assets edit form and create inventory item from asset form, use tabs to show only relevant fields.
=> use tabs in templates

netbox_inventory/forms/bulk.py, netbox_inventory/forms/models.py, netbox_inventory/templates/netbox_inventory/asset_edit.html
since we allow setting these fields on import from #88 onward it makes sense to allow also during create edit or bulk edit
=> add option to edit tenant and contact on asset create/edit

README.md, netbox_inventory/__init__.py, netbox_inventory/forms/create.py
New config option to add a way to pre fill tag and/or name when creating hardware from an asset
=> add asset inventory prefill

netbox_inventory/templates/netbox_inventory/inventoryitemgroup.html, netbox_inventory/views/inventoryitem_group.py
I had to change the way data is being passed to the template for a cleaner and easier way to loop over that data.
Let me know if something needs to be refactored in `inventoryitem_group.py` file. Python is not my go-to language 😄
=> Design change related to issue #100

netbox_inventory/templates/netbox_inventory/supplier.html, netbox_inventory/urls.py, netbox_inventory/views/supplier.py
this follows change made in netbox#12460
=> supplier contact assignments are shown in separate tab

netbox_inventory/models.py
Asset clone will now prefill all fields except serial number
=> add more clone fields to Asset

netbox_inventory/forms/bulk.py, netbox_inventory/tests/delivery/test_api.py, netbox_inventory/tests/delivery/test_views.py
and add unit tests for Delivery model
=> Fix Delivery CSV import

netbox_inventory/filtersets.py
Filtering assets for `tenant_any=<tenant_slug>` will match tenant_slug for both - asset.owner and asset.tenant
=> add filter for assets on any tenant or owner

netbox_inventory/filtersets.py
we already have tenant_any that filters on tenant.slug. Add tenant_any_id to filter on tenant.id as well
=> add tenant_any_id filter on assets

netbox_inventory/graphql.py
Adds `graphql` support following guidance from https://github.com/netbox-community/netbox-plugin-tutorial/blob/main/tutorial/step10-graphql-api.md
=> Add graphql support

netbox_inventory/forms/reassign.py
For a better overview of which fields belong to the new or old asset, fieldsets should provide some separation and clarity.
=> Split reassign form in fieldsets

netbox_inventory/filtersets.py
=> additional filtering on assets

netbox_inventory/filtersets.py, netbox_inventory/forms/filters.py
Adds filters to asset lists:
- device_role_id=2
- device_role=slug
- inventoryitem_role_id=2
- inventoryitem_role=slug
=> Add filters on device role and inventory item role to assets

README.md, netbox_inventory/navigation.py, netbox_inventory/search.py, netbox_inventory/utils.py
- cleanup menu code to drop support for old netbox versions
- in global search, assets will not show additional attributes
- use netbox function to get plugin settings
=> small improvements to global search & menu

netbox_inventory/migrations/0009_add_rack.py
don't depend on core netbox apps in migration
=> fix recent migration dependencies

netbox_inventory/templates/netbox_inventory/delivery.html
=> when creating asset via delivery view pre-fill purchase field

netbox_inventory/views/asset.py, netbox_inventory/views/delivery.py, netbox_inventory/views/inventoryitem_group.py, netbox_inventory/views/inventoryitem_type.py, netbox_inventory/views/purchase.py, netbox_inventory/views/supplier.py
=> add filtersets to bulk delete views
